INSERT INTO PERFIL (ID, NOME) VALUES (1, 'MUNICIPE');
INSERT INTO PERFIL (ID, NOME) VALUES (2, 'SERVIDOR');

INSERT INTO USUARIO (ID, NOME, SOBRENOME, EMAIL, USUARIO, SENHA, STATUS, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, DATA_CRIACAO, DATA_ATUALIZACAO, PERFIL_ID) VALUES (10, 'JOAO', 'SANTO CRISTO', 'santocristo.joao@dominio.com', 'j-santocristo', '1234', 'ACTIVE', 'CPF', '12332111122', now(), now(), 1);
INSERT INTO USUARIO (ID, NOME, SOBRENOME, EMAIL, USUARIO, SENHA, STATUS, TIPO_DOCUMENTO, NUMERO_DOCUMENTO, DATA_CRIACAO, DATA_ATUALIZACAO, PERFIL_ID) VALUES (11, 'MARIA', 'LUCIA', 'lucia.maria@dominio.com', 'm-lucia', '1234', 'ACTIVE', 'CPF', '12332111133', now(), now(), 2);